ARG BASE_IMG=ghcr.io/domstolene/redhat-github-actions/runner:latest
FROM $BASE_IMG AS node-runner

USER root

# https://nodejs.org/en/download/package-manager/#centos-fedora-and-red-hat-enterprise-linux
# 22 is LTS
RUN dnf install nodejs -y

USER $UID
