name: Nightly build

on:
  workflow_dispatch:
  schedule:
    # once every day
    - cron: '0 0 * * *'

env:
  REGISTRY_URL: ghcr.io/domstolene/openshift-actions-runners

  PLAYWRIGHT_IMG_NAME: playwright-runner
  PLAYWRIGHT_IMG_DIR: playwright
  IMG_TAGS: latest

jobs:
  update_images:
    name: Update images
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push playwright image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.PLAYWRIGHT_IMG_DIR }}
          file: ${{ env.PLAYWRIGHT_IMG_DIR }}/Containerfile
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.PLAYWRIGHT_IMG_NAME }}:${{ env.IMG_TAGS }}
